In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
a= np.array([1,2,3])
b= np.array([4,5,6])

In [5]:
import numpy as np

In [6]:
np.sqrt(np.dot(b-a,b-a))

5.196152422706632

In [7]:
X = np.array([[1,2],[2,3],[3,4],[4,5],[5,6]])

In [8]:
X

array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 5],
       [5, 6]])

In [9]:
cluster_group = np.array([0,1,1,0,0])

np.unique(cluster_group)

array([0, 1])

In [10]:
for type in np.unique(cluster_group):

  print(type)

0
1


In [11]:
X[cluster_group == 0]

array([[1, 2],
       [4, 5],
       [5, 6]])

In [12]:
X[cluster_group == 0].mean()

3.8333333333333335

In [13]:
X[cluster_group == 0].mean(axis=1)

array([1.5, 4.5, 5.5])